In [26]:
# 0-D array
import numpy as np
a = np.array(42)
print(a)
print(a.ndim)

42
0


In [20]:
# 1-D array
b = np.array([42])
print(b)

[42]


In [22]:
# 2-D array
import numpy as np
c = np.array([[42]])
print(c)

[[42]]


In [23]:
# 3-D array
import numpy as np
d = np.array([[[42]]])
print(d)

[[[42]]]


In [27]:
# ndim
e = np.array([1,2,3,4,5])
print(e.ndim)

1


In [2]:
# indexing 
a = np.array([1,2,3,4])
print(a[1])

2


In [5]:
a = np.array([[1,2,8],[4,5,6]])
print(a)
print("3rd element on 1st row:", a[0,2])

[[1 2 8]
 [4 5 6]]
3rd element on 1st row: 8


In [9]:
# slicing
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[2:])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b[1:])
print(a[-3:-1])
print(a[::3])

[3 4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]
[7 8]
[1 4 7]


In [19]:
# slicing of 2-D arrays
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a[1,:])
print(a[1:, 0:2])

[4 5 6]
[[ 4  5]
 [ 7  8]
 [10 11]]
